force-app/main/default/objects/Meetup__c/Meetup__c.object-meta.xml
<CustomObject>
    <description>This object is intended to be used to track meetups for users as part of the Meetup app</description>
    <label>Meetup</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Meetups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Meetup__c/fields/Registration_Code__c.field-meta.xml
<CustomField>
    <fullName>Registration_Code__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>The registration code that will be used to find a meetup on the registration page</description>
    <label>Registration Code</label>
    <length>8</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/H_Meetup.cls
public with sharing class H_Meetup {
    public void handleBeforeInsert(List<Meetup__c> newMeetups) {
        generateRegistrationCode(newMeetups);
    }

    public void generateRegistrationCode(List<Meetup__c> meetupsToProcess) {
        for(Meetup__c meetup : meetupsToProcess) {
            meetup.Registration_Code__c = generateRandomString(8);
        }
    }

    //Method to generate a random string from Developer forums - https://salesforce.stackexchange.com/questions/43823/how-do-i-generate-a-random-string
    //This method does not explicitly check for a unique value among all registrations but has a large enough value set that collision is unlikely.
    public String generateRandomString(Integer len) {
        final String chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789abcdefghijklmnopqrstuvwxyz';
        String randStr = '';
        while (randStr.length() < len) {
           Integer idx = Math.mod(Math.abs(Crypto.getRandomInteger()), chars.length());
           randStr += chars.substring(idx, idx+1);
        }
        return randStr; 
    }
}