force-app/main/default/objects/Meetup__c/Meetup__c.object-meta.xml
<CustomObject>
    <description>This object is intended to be used to track meetups for users as part of the Meetup app</description>
    <label>Meetup</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Meetups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Meetup_Registration__c/Meetup_Registration__c.object-meta.xml
<CustomObject>
    <description>This object is intended to track registrations for a meetup as part of the Meetup app</description>
    <label>Meetup Registration</label>
    <nameField>
        <displayFormat>R-{0000000000}</displayFormat>
        <label>Registration Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Meetup Registrations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Meetup_Registration__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>The users email who is registering for a meetup</description>
    <label>Email</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Meetup_Registration__c/fields/Meetup__c.field-meta.xml
<CustomField>
    <fullName>Meetup__c</fullName>
    <description>Master-Detail with Meetup to enforce sharing and required realtionship</description>
    <label>Meetup</label>
    <referenceTo>Meetup__c</referenceTo>
    <relationshipLabel>Meetup Registrations</relationshipLabel>
    <relationshipName>Meetup_Registrations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/MeetupRegistrationController.cls
public with sharing class MeetupRegistrationController {
    @AuraEnabled
    public static Meetup_Registration__c createMeetupRegistration(Meetup_Registration__c meetupRegistrationObject){
        //Each email must be unique per Meetup.
        Meetup__c meetupToRegisterFor = [
            SELECT Id, (SELECT Email__c FROM Meetup_Registrations__r WHERE Email__c = :meetupRegistrationObject.Email__c)  
            FROM Meetup__c 
            WHERE Id = :meetupRegistrationObject.Meetup__c
        ];
        if(meetupToRegisterFor.Meetup_Registrations__r.size() > 0) {
            throw new AuraHandledException('A registration with an email of '+meetupToRegisterFor.Meetup_Registrations__r[0].Email__c+' already exists for this meetup. Please check the home page for a list of your existing registrations.');
        } else {
            try {
                insert meetupRegistrationObject;
                return meetupRegistrationObject;
            } catch (Exception e) {
                throw new AuraHandledException(e.getMessage());
            }
        }
    }
}