force-app/main/default/objects/Meetup__c/Meetup__c.object-meta.xml
<CustomObject>
    <description>This object is intended to be used to track meetups for users as part of the Meetup app</description>
    <label>Meetup</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Meetups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Meetup__c/fields/Registration_Limit__c.field-meta.xml
<CustomField>
    <fullName>Registration_Limit__c</fullName>
    <description>The max # of registrations allowed for this Meetup</description>
    <label>Registration Limit</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Meetup__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>The status of the Meetup. New registrations are only allowed when status is &apos;Open&apos;.</description>
    <inlineHelpText>The status of the Meetup</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Meetup_Registration__c/Meetup_Registration__c.object-meta.xml
<CustomObject>
    <description>This object is intended to track registrations for a meetup as part of the Meetup app</description>
    <label>Meetup Registration</label>
    <nameField>
        <displayFormat>R-{0000000000}</displayFormat>
        <label>Registration Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Meetup Registrations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Meetup_Registration__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>The users email who is registering for a meetup</description>
    <label>Email</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Meetup_Registration__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <description>The first name of the user who is registering</description>
    <label>First Name</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Meetup_Registration__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <description>The last name of the user who is registering for the meetup</description>
    <label>Last Name</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Meetup_Registration__c/fields/Meetup__c.field-meta.xml
<CustomField>
    <fullName>Meetup__c</fullName>
    <description>Master-Detail with Meetup to enforce sharing and required realtionship</description>
    <label>Meetup</label>
    <referenceTo>Meetup__c</referenceTo>
    <relationshipLabel>Meetup Registrations</relationshipLabel>
    <relationshipName>Meetup_Registrations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/MeetupRegistrationController_Test.cls
@IsTest
public with sharing class MeetupRegistrationController_Test {
    /**
    * Test class covering the MeetupRegistrationController Apex class
    */
    @TestSetup
    static void setupMeetupRegistrationData() {
        Meetup__c testMeetup = new Meetup__c(
            Name = 'Test Meetup',
            Status__c = 'Open',
            Registration_Limit__c = 1
        );
        insert testMeetup;
        
        Meetup_Registration__c testRegistration = new Meetup_Registration__c(
            First_Name__c = 'Test',
            Last_Name__c = 'Test',
            Email__c = 'Test@test.com',
            Meetup__c = testMeetup.Id
        );

        insert testRegistration;
    }

    @IsTest
    static void testSameEmail() {
        Meetup__c testMeetup = [SELECT Id FROM Meetup__c LIMIT 1];
        try{
            Meetup_Registration__c testRegistration = new Meetup_Registration__c(
                First_Name__c = 'Test',
                Last_Name__c = 'Test',
                Email__c = 'Test@test.com',
                Meetup__c = testMeetup.Id
            );
            MeetupRegistrationController.createMeetupRegistration(testRegistration);
        }catch(AuraHandledException e){
            System.assertNotEquals(e, null);
        }
    }

    @IsTest
    static void testPositiveInsert() {
        Meetup__c testMeetup = [SELECT Id,Registration_Limit__c FROM Meetup__c LIMIT 1];
        testMeetup.Registration_Limit__c = 2;
        Meetup_Registration__c testRegistration = new Meetup_Registration__c(
                First_Name__c = 'Test',
                Last_Name__c = 'Test',
                Email__c = 'Test+2@test.com',
                Meetup__c = testMeetup.Id
        );
        
        Meetup_Registration__c returnedRegistration = MeetupRegistrationController.createMeetupRegistration(testRegistration);
        System.assertNotEquals(returnedRegistration, null);
    }
}