force-app/main/default/objects/Meetup__c/Meetup__c.object-meta.xml
<CustomObject>
    <description>This object is intended to be used to track meetups for users as part of the Meetup app</description>
    <label>Meetup</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Meetups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Meetup__c/fields/Registration_Code__c.field-meta.xml
<CustomField>
    <fullName>Registration_Code__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>The registration code that will be used to find a meetup on the registration page</description>
    <label>Registration Code</label>
    <length>8</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Meetup__c/fields/Registration_Limit__c.field-meta.xml
<CustomField>
    <fullName>Registration_Limit__c</fullName>
    <description>The max # of registrations allowed for this Meetup</description>
    <label>Registration Limit</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Meetup__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>The status of the Meetup. New registrations are only allowed when status is &apos;Open&apos;.</description>
    <inlineHelpText>The status of the Meetup</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/H_Meetup_Test.cls
@IsTest
public with sharing class H_Meetup_Test {
    /**
    * Test class covering the T_Meetup trigger and H_Meetup Apex class
    * Test covers insert of Meetup__c
    */
    @IsTest
    static void testMeetupInsert() {
        
        insert new Meetup__c(
            Name = 'Test Meetup',
            Status__c = 'Open',
            Registration_Limit__c = 500
        );

        //Assert to verify record was inserted
        List<Meetup__c> foundMeetups = [SELECT Id,Registration_Code__c FROM Meetup__c];
        System.assertEquals(foundMeetups.size(),1);

        //Assert to verify registration code was added by trigger/handler
        System.assertNotEquals(foundMeetups[0].Registration_Code__c, null);
    }
}