force-app/main/default/objects/Meetup__c/Meetup__c.object-meta.xml
<CustomObject>
    <description>This object is intended to be used to track meetups for users as part of the Meetup app</description>
    <label>Meetup</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Meetups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Meetup__c/fields/Registration_Code__c.field-meta.xml
<CustomField>
    <fullName>Registration_Code__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>The registration code that will be used to find a meetup on the registration page</description>
    <label>Registration Code</label>
    <length>8</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Meetup__c/fields/Registration_Limit__c.field-meta.xml
<CustomField>
    <fullName>Registration_Limit__c</fullName>
    <description>The max # of registrations allowed for this Meetup</description>
    <label>Registration Limit</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Meetup__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>The status of the Meetup. New registrations are only allowed when status is &apos;Open&apos;.</description>
    <inlineHelpText>The status of the Meetup</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Meetup_Registration__c/Meetup_Registration__c.object-meta.xml
<CustomObject>
    <description>This object is intended to track registrations for a meetup as part of the Meetup app</description>
    <label>Meetup Registration</label>
    <nameField>
        <displayFormat>R-{0000000000}</displayFormat>
        <label>Registration Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Meetup Registrations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Meetup_Registration__c/fields/Meetup__c.field-meta.xml
<CustomField>
    <fullName>Meetup__c</fullName>
    <description>Master-Detail with Meetup to enforce sharing and required realtionship</description>
    <label>Meetup</label>
    <referenceTo>Meetup__c</referenceTo>
    <relationshipLabel>Meetup Registrations</relationshipLabel>
    <relationshipName>Meetup_Registrations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/MeetupController.cls
public with sharing class MeetupController {
    @AuraEnabled(cacheable=true)
    public static Meetup__c getSingleMeetup(String registrationCode) {
        //Performing field value validation in Apex controller to satisfy requirements 
        // ● All business rules must be reinforced in apex for security reasons.
        //● The user can only register if the Meetup status is Open.
        //● The user cannot register when the total # of registrations exceed the registration limit for this Meetup.
        Meetup__c meetupToReturn = [
            SELECT Id, Name, Status__c,Registration_Limit__c, (SELECT Id FROM Meetup_Registrations__r)  
            FROM Meetup__c
            WHERE Registration_Code__c = :registrationCode
            WITH SECURITY_ENFORCED
            LIMIT 1
        ];
        if(meetupToReturn == null) {
            throw new AuraHandledException('No meetup was found with that registration code. Please verify the code and try again!');      
        } else if(meetupToReturn.Meetup_Registrations__r.size() >= meetupToReturn.Registration_Limit__c) {
            throw new AuraHandledException('The number of registrations for this meetup have met or exceeded the registration limit. Your registration can not be added at this time.');      
        } else if(meetupToReturn.Status__c != 'Open') {
            throw new AuraHandledException('The meetup is not in the Open status. Your registration can not be added at this time.');      
        } else {
            return meetupToReturn;
        }
    }
}